[package]
name = "serial_test_test"
description = "External testing crate for serial_test"
license = "MIT"
version = "4.0.1"
edition = "2018"
rust-version.workspace = true

[package.metadata.cargo-all-features]
skip_optional_dependencies = true

[dependencies]
env_logger = { version = ">=0.6.1", default-features = false }
lock_api = { version = "^0.4.7", default-features = false }
log = { version = ">=0.4.4", default-features = false }
once_cell = { version = "^1.19", default-features = false }
parking_lot = { version = "^0.12", default-features = false }
scoped-tls = { version = "1", default-features = false, optional = true }
serial_test = { path = "../serial_test", default-features = false }
wasm-bindgen-test = { version = ">=0.3.50, <0.4", default-features = false, features = ["std"], optional = true }

[dev-dependencies]
actix-rt = { version = "^2.8", default-features = false, features = ["macros"] }
futures-util = { version = "^0.3", default-features = false }
ntest = "0.9.5"
tokio = { version = ">=1.38.2, <2", default-features = false, features = ["macros", "rt", "rt-multi-thread"] }

[features]
default = ["async", "logging"]
async = ["dep:scoped-tls", "dep:wasm-bindgen-test", "serial_test/async"]
file_locks = ["serial_test/file_locks"]
logging = ["serial_test/logging", "serial_test/test_logging"]
